### PR TITLE
Sign In and Sign Up added

### LINKED ISSUE #2: Users should sign in and sign up in Walletify

### PR DESCRIPTION
**Pull request by lucasSaavedra123**

### CODE REVIEW

**Comment by nachotornati** [comment]
Ok

**Comment by lucasSaavedra123** [comment]
I share the colors that the team selected as possible candidates:

Candidate One:
- #9CE37D
- #87B37A
- #77867F
- #4C2C72
- #4B296B

image

Candidate Two:
- #14453D
- #3D7068
- #43C59E
- #3DFAFF
- #48BEFF

image

**Comment by lucasSaavedra123** [comment]
Things To Do:

- [x] Add/Check Style
- [x] Add Profile
- [x] Font Setting
- [x] Verify Authentication
- [x] Add Sidebar
- [x] Change Password

**Comment by lucasSaavedra123** [comment]
- [x] Verify UX
- [x] Verify Colors and Fonts
- [x] All Possible Refactors
- [x] Add notifications (This is possible with material-ui)

**Comment by lucasSaavedra123** [comment]
Everything Done.

**Comment by lucasSaavedra123** [comment]
The team will discuss colors with clients. By now, Green, Black, and White are predominant.

**Comment by nachotornati** [comment]
Nice!

**Review by nachotornati — COMMENTED** [review]
Approved

**Review by nachotornati — APPROVED** [review]

**Pull request merged**
